UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementSystemApp.Gateway;
using UniversityCourseAndResultManagementSystemApp.Models;

namespace UniversityCourseAndResultManagementSystemApp.Controllers
{
    public class CourseController : Controller
    {
        private DatabaseGateway newDatabaseGateway = new DatabaseGateway();
        // GET: Course
        

        public List<Department> LoadDeptDropBox()
        {
            List<Department> deptList = new List<Department>();
            newDatabaseGateway.Command.CommandText = "SELECT * FROM DEPARTMENT;";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                Department newDepartment = new Department
                {
                    DeptCode = reader["DeptCode"].ToString(),
                    DeptName = reader["DeptName"].ToString()
                };
                deptList.Add(newDepartment);

            }
            newDatabaseGateway.Connection.Close();

            return deptList;

        }

        public List<string> LoadSemesterDropBox()
        {
            List<string> semList = new List<string>();
            newDatabaseGateway.Command.CommandText = "SELECT * FROM SEMESTER;";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                semList.Add(reader["SemNo"].ToString());

            }
            newDatabaseGateway.Connection.Close();

            return semList;
        }

        public ActionResult SaveCourse(Course newCourse)
        {
            int affectedRow = 0;
            if (newCourse.DeptCode != null)
            {
                /*newDatabaseGateway.Command.CommandText = "INSERT INTO COURSE VALUES('" + newCourse.CourseCode + "','" +
                                                         newCourse.CourseName + "','" + newCourse.CourseCredit + "','" +
                                                         newCourse.CourseDes + "','" + newCourse.DeptCode + "','" +
                                                         newCourse.CourseSemester + "','Not Assigned Yet');";*/
                newDatabaseGateway.Command.CommandText = "INSERT INTO COURSE(CourseCode, CourseName, CourseCredit, CourseDes, DeptCode, CourseSemester, FACULTY) " +
                                                         "SELECT @courseCode, @courseName, @courseCredit, @courseDes, @deptCode, @courseSemester, @faculty " +
                                                         "WHERE NOT EXISTS (SELECT * FROM COURSE WHERE CourseCode = @courseCode)";
                newDatabaseGateway.Command.Parameters.AddWithValue("@courseCode", newCourse.CourseCode);
                newDatabaseGateway.Command.Parameters.AddWithValue("@courseName", newCourse.CourseName);
                newDatabaseGateway.Command.Parameters.AddWithValue("@courseCredit", newCourse.CourseCredit);
                newDatabaseGateway.Command.Parameters.AddWithValue("@courseDes", newCourse.CourseDes);
                newDatabaseGateway.Command.Parameters.AddWithValue("@deptCode", newCourse.DeptCode);
                newDatabaseGateway.Command.Parameters.AddWithValue("@courseSemester", newCourse.CourseSemester);
                newDatabaseGateway.Command.Parameters.AddWithValue("@faculty", "Not Assigned Yet");


                newDatabaseGateway.Connection.Open();
                affectedRow = newDatabaseGateway.Command.ExecuteNonQuery();
                newDatabaseGateway.Connection.Close();
                if (affectedRow == 0)
                {
                    ViewBag.message = "Course Already Exists !!!!!!";
                }
                else
                {
                    ViewBag.message = "Successfully Saved !!!!!!";
                }
            }

            ViewBag.deptList = LoadDeptDropBox();
            ViewBag.semList = LoadSemesterDropBox();
           
            return View();
        }

        public ActionResult AddCourse(Course newCourse)
        {
            int affectedRow = 0;
            if (newCourse.DeptCode != null)
            {
                /*newDatabaseGateway.Command.CommandText = "INSERT INTO COURSE VALUES('" + newCourse.CourseCode + "','" +
                                                         newCourse.CourseName + "','" + newCourse.CourseCredit + "','" +
                                                         newCourse.CourseDes + "','" + newCourse.DeptCode + "','" +
                                                         newCourse.CourseSemester + "','Not Assigned Yet');";*/
                newDatabaseGateway.Command.CommandText = "INSERT INTO COURSE(CourseCode, CourseName, CourseCredit, CourseDes, DeptCode, CourseSemester, FACULTY) " +
                                                         "SELECT @courseCode, @courseName, @courseCredit, @courseDes, @deptCode, @courseSemester, @faculty " +
                                                         "WHERE NOT EXISTS (SELECT * FROM COURSE WHERE CourseCode = @courseCode)";
                newDatabaseGateway.Command.Parameters.AddWithValue("@courseCode", newCourse.CourseCode);
                newDatabaseGateway.Command.Parameters.AddWithValue("@courseName", newCourse.CourseName);
                newDatabaseGateway.Command.Parameters.AddWithValue("@courseCredit", newCourse.CourseCredit);
                newDatabaseGateway.Command.Parameters.AddWithValue("@courseDes", newCourse.CourseDes);
                newDatabaseGateway.Command.Parameters.AddWithValue("@deptCode", newCourse.DeptCode);
                newDatabaseGateway.Command.Parameters.AddWithValue("@courseSemester", newCourse.CourseSemester);
                newDatabaseGateway.Command.Parameters.AddWithValue("@faculty", "Not Assigned Yet");


                newDatabaseGateway.Connection.Open();
                affectedRow = newDatabaseGateway.Command.ExecuteNonQuery();
                newDatabaseGateway.Connection.Close();
                if (affectedRow == 0)
                {
                    ViewBag.message = "Data Already Exists !!!!!!";
                }
                else
                {
                    ViewBag.message = "Successfully Saved !!!!!!";
                }
            }

            ViewBag.deptList = LoadDeptDropBox();
            ViewBag.semList = LoadSemesterDropBox();

            return View();
        }

        

        public JsonResult GetCoursesByDepartmentCode(string DeptCode)
        {
            List<Course> courses = new List<Course>();
            newDatabaseGateway.Command.CommandText = "SELECT * FROM COURSE WHERE DeptCode = '"+ DeptCode +"';";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                Course newCourse = new Course
                {
                    CourseCode = reader["CourseCode"].ToString(),
                    CourseName = reader["CourseName"].ToString(),
                    CourseSemester = reader["CourseSemester"].ToString(),
                    CourseAssignedTo = reader["FACULTY"].ToString()
                };
                courses.Add(newCourse);
            }
            newDatabaseGateway.Connection.Close();
            return Json(courses);
        }

        public ActionResult ViewCourseSatistics()
        {
            ViewBag.deptList = LoadDeptDropBox();
            return View();
        }

        public ActionResult UnassignAllCourses()
        {
            int affectedRow = 0;
            newDatabaseGateway.Command.CommandText = "UPDATE COURSE SET FACULTY = 'Not Assigned Yet'";
            newDatabaseGateway.Connection.Open();
            affectedRow = newDatabaseGateway.Command.ExecuteNonQuery();
            newDatabaseGateway.Connection.Close();
            if (affectedRow == 0)
            {
                ViewBag.message = "Error!!";
            }
            else
            {
                ViewBag.message = "Successfully unassigned.!!!";
            }
            return View();
        }
    }
}

UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementSystemApp.Gateway;
using UniversityCourseAndResultManagementSystemApp.Models;

namespace UniversityCourseAndResultManagementSystemApp.Controllers
{
    public class DepartmentController : Controller
    {
        private DatabaseGateway newDataBaseGateway = new DatabaseGateway();
        // GET: Department
        public ActionResult SaveDepartment(Department newdepartment)
        {
            int affectedRow = 0;
            if (newdepartment.DeptCode != null && newdepartment.DeptName != null)
            {
                //newDataBaseGateway.Command.CommandText = "INSERT INTO DEPARTMENT VALUES('" + newdepartment.DeptCode + "','" + newdepartment.DeptName + "');";
                newDataBaseGateway.Command.CommandText = "INSERT INTO DEPARTMENT(DeptCode, DeptName) SELECT @deptCode, @deptName WHERE NOT EXISTS(SELECT * FROM DEPARTMENT WHERE DeptCode = @deptCode or DeptName = @deptName);";
                newDataBaseGateway.Command.Parameters.AddWithValue("@deptCode", newdepartment.DeptCode);
                newDataBaseGateway.Command.Parameters.AddWithValue("@deptName", newdepartment.DeptName);
                newDataBaseGateway.Connection.Open();
                affectedRow = newDataBaseGateway.Command.ExecuteNonQuery();
                newDataBaseGateway.Connection.Close();
                if (affectedRow == 0)
                {
                    ViewBag.message = "Department Code or Name already Exsts !!!";
                }
                else
                {
                    ViewBag.message = "Successfully Saved...!!!";
                }
            }
            

            return View();
        }

        public ActionResult newDepartment(Department newdepartment)
        {
            int affectedRow = 0;
            if (newdepartment.DeptCode != null && newdepartment.DeptName != null)
            {
                //newDataBaseGateway.Command.CommandText = "INSERT INTO DEPARTMENT VALUES('" + newdepartment.DeptCode + "','" + newdepartment.DeptName + "');";
                newDataBaseGateway.Command.CommandText = "INSERT INTO DEPARTMENT(DeptCode, DeptName) SELECT @deptCode, @deptName WHERE NOT EXISTS(SELECT * FROM DEPARTMENT WHERE DeptCode = @deptCode or DeptName = @deptName);";
                newDataBaseGateway.Command.Parameters.AddWithValue("@deptCode", newdepartment.DeptCode);
                newDataBaseGateway.Command.Parameters.AddWithValue("@deptName", newdepartment.DeptName);
                newDataBaseGateway.Connection.Open();
                affectedRow = newDataBaseGateway.Command.ExecuteNonQuery();
                newDataBaseGateway.Connection.Close();
                if (affectedRow == 0)
                {
                    ViewBag.message = "Department Code or Name already Exsts !!!";
                }
                else
                {
                    ViewBag.message = "Successfully Saved...!!!";
                }
            }
            

            return View();
        }

        public ActionResult ViewDepartment()
        {
            newDataBaseGateway.Command.CommandText = "SELECT * FROM DEPARTMENT;";
            newDataBaseGateway.Connection.Open();
            SqlDataReader reader = newDataBaseGateway.Command.ExecuteReader();

            List<Department> deptList = new List<Department>();

            while (reader.Read())
            {
                Department newDepartment = new Department
                {
                    DeptCode = reader["DeptCode"].ToString(),
                    DeptName = reader["DeptName"].ToString()
                };
                deptList.Add(newDepartment);

            }
            newDataBaseGateway.Connection.Close();

            ViewBag.deptList = deptList;
            return View();
        }
    }
}

UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityCourseAndResultManagementSystemApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Views/Shared/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Daffodil International University</title>
    <!-- Stylesheets -->
    <link rel="shortcut icon" type="image/png" href="images/favicon.png" />
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- Responsive -->
    <link href="~/css/responsive.css" rel="stylesheet" />
    

    
    

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    <style>
        #success_message{ display: none;}
        #error_message{ display: none;}
        

        .table-fixed {
            width: 80%;
            background-color: #f3f3f3;
            margin-left: 10%;
            margin-right: 10%;
        }
        .table-fixed thead tr th {
            background-color: #f39c12;
            border-color: #e67e22;
        }
        .table-fixed thead {
            width: 97%;
        }

        .table-fixed tbody {
            height: 230px;
            overflow-y: auto;
            width: 100%;
        }

        .table-fixed thead, .table-fixed tbody, .table-fixed tr, .table-fixed td, .table-fixed th {
            display: block;
        }

        .table-fixed tbody td, .table-fixed thead > tr > th {
            float: left;
            border-bottom-width: 0;
        }
        
    </style>
    
    
</head>
<body class="theme-green">
    <div class="page-wrapper">
        <!-- Preloader -->
        <div class="preloader"></div>
        <!-- Main Header / Style One-->

        <header class="main-header header-style-one">
            <!-- Header Top
            <div class="header-top">
            <div class="container clearfix ptn pbn">
            <!--Top Left
            <div class="top-left pull-left">
            <ul class="info-nav clearfix">
            <li>
            <!--Social Links
            <div class="social-links pull-left"> <span class="text-theme-color">Follow Us</span> : <a href="#"><span class="fa fa-facebook-f"></span></a> <a href="#"><span class="fa fa-twitter"></span></a> <a href="#"><span class="fa fa-google-plus"></span></a> <a href="#"><span class="fa fa-linkedin"></span></a> </div>
            </li>
            <li><a href="mailto:yourmail@gmail.com"><span class="icon icon-Mail mr10"></span>Opening Hours</a></li>
            </ul>
            </div>
            <!--Top Right
            <div class="top-right pull-right clearfix">
            <!--Lang Bar
            <ul class="info-nav clearfix">
                <li><a href="#"><i class="icon icon-Phone mr10 text-theme-color"></i><span class="ml5">Emergency Line</span> (+123) 2456 987</a></li>
                <li><a href="#" class="text-uppercase appoinment"><i class="icon icon-Pen mr10 text-theme-color "></i> Make an appoinment</a></li>
            </ul>
            </div>
            </div>
            </div>
            Header Top End -->
            <!--Header-Main Box-->
            <div class="header-mainbox">
                <div class="container ptn pbn">
                    <div class="clearfix">
                        <!--  <div class="pull-left">
                            <div class="logo"> <a href="index-mp-layout1.html"><img src="images/logo.png" alt="" title="Green"></a> </div>
                        </div> -->
                        <div class="outer-box clearfix">
                            <!-- Main Menu -->
                            <nav class="main-menu logo-outer">
                                <div class="navbar-header">
                                    <!-- Toggle Button -->
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                                </div>
                                <div class="navbar-collapse collapse clearfix">
                                    <ul class="navigation clearfix">
                                        <li class="">
                                            @Html.ActionLink("HOME", "Index", "Home")
                                        </li>

                                        <li class="dropdown">
                                            <a href="#">DEPARTMENT</a>
                                            <ul>
                                                <li>@Html.ActionLink("SAVE DEPARTMENT", "SaveDepartment", "Department")</li>
                                                <li>@Html.ActionLink("VIEW ALL DEPARTMENT", "ViewDepartment", "Department")</li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#">COURSE</a>
                                            <ul>
                                                <li>@Html.ActionLink("ADD COURSE", "SaveCourse", "Course")</li>
                                                <li>@Html.ActionLink("COURSE STATISTICES", "ViewCourseSatistics", "Course")</li>
                                                <li>@Html.ActionLink("UNASSIGNED ALL COURSES", "UnassignAllCourses", "Course")</li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#">TEACHER</a>
                                            <ul>
                                                <li>@Html.ActionLink("ADD TEACHER", "SaveTeacher", "Teacher")</li>
                                                <li>@Html.ActionLink("COURSE ASSIGNED TO TEACHER", "CourseAssignToTeacher", "Teacher")</li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#">STUDENT</a>
                                            <ul>
                                                <li>@Html.ActionLink("REGISTER STUDENT", "RegisterStudent", "Student")</li>
                                                <li>@Html.ActionLink("ENDROLL IN COURSE", "EnrollCourse", "Student")</li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#">CLASS ROOM</a>
                                            <ul>
                                                <li>@Html.ActionLink("ALLOCATE CLASS ROOM", "AllocateClassRoom", "ClassRoom")</li>
                                                <li>@Html.ActionLink("CLASS SCHEDULE AND ROOM INFORMATION", "ClassRoomInfo", "ClassRoom")</li>
                                                <li>@Html.ActionLink("UNALLOCATE CLASS ROOM", "UnAllocateClassRoom", "ClassRoom")</li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#">RESULT</a>
                                            <ul>
                                                <li>@Html.ActionLink("SAVE STUDENT RESULT", "SaveStudentResult", "Result")</li>
                                                <li>@Html.ActionLink("VIEW RESULT", "ViewResult", "Result")</li>
                                            </ul>
                                        </li>
                                        @Html.Partial("_LoginPartial")
                                    </ul>

                                </div>
                            </nav>
                            <!-- Main Menu End-->
                        </div>
                    </div>
                </div>
            </div>
            <!--Header Main Box End-->
        </header>

        @RenderBody()

    </div>

    <!--End Main Header -->
    <div class="scroll-to-top scroll-to-target" data-target=".main-header"><span class="fa fa-long-arrow-up"></span></div>

   

<script src="~/js/jquery.js"></script>
<script src="~/js/all-jquery.js"></script>
<script src="~/js/script.js"></script>
    


@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    

    
</body>
</html>

UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Save Department", "SaveDepartment", "Department")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @RenderBody()
<div class="container body-content">
    
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

 

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
    
    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
<script>
    $(document).ready(function () {
        $("#saveDepartment").validate({
            rules: {
                DeptCode: "required",
                DeptName: {
                    required: true
                }
            },
            messages: {

            }
        });

    });
</script>
</body>
</html>