UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Controllers/ClassRoomController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementSystemApp.Gateway;
using UniversityCourseAndResultManagementSystemApp.Models;

namespace UniversityCourseAndResultManagementSystemApp.Controllers
{
    public class ClassRoomController : Controller
    {
        private DatabaseGateway newDatabaseGateway = new DatabaseGateway();

        public List<Department> LoadDeptDropBox()
        {
            List<Department> deptList = new List<Department>();
            newDatabaseGateway.Command.CommandText = "SELECT * FROM DEPARTMENT;";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                Department newDepartment = new Department
                {
                    DeptCode = reader["DeptCode"].ToString(),
                    DeptName = reader["DeptName"].ToString()
                };
                deptList.Add(newDepartment);

            }
            newDatabaseGateway.Connection.Close();

            return deptList;

        }

        List<int> GetAllRooms()
        {
            List<int> rooms = new List<int>();
            newDatabaseGateway.Command.CommandText = "SELECT * FROM ROOM;";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                rooms.Add(Convert.ToInt32(reader["RoomNo"].ToString()));
            }
            newDatabaseGateway.Connection.Close();
            return rooms;
        }

        List<string> GetAllDay()
        {
            List<string> days = new List<string>();
            newDatabaseGateway.Command.CommandText = "SELECT * FROM WEEKDAY;";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                days.Add(reader["DAY"].ToString());
            }
            newDatabaseGateway.Connection.Close();
            return days;
        }

        public RoomAllocation GetAllocationInfo(string CourseCode)
        {
            RoomAllocation prevAllocation = new RoomAllocation();
            newDatabaseGateway.Command.CommandText = "SELECT * FROM ROOM_SCHEDULE WHERE CourseCode = '"+ CourseCode +"' AND Valid = 'True';";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                prevAllocation.Day = reader["Day"].ToString();
                prevAllocation.RoomNo = reader["RoomNo"].ToString();
                prevAllocation.FromTime = reader["FromTime"].ToString();
                prevAllocation.ToTime = reader["ToTime"].ToString();
            }
            newDatabaseGateway.Connection.Close();
            return prevAllocation;
        }

        public bool LessThan(string str1, string str2)
        {
            int num1, num2, num3, num4;
            num1 = (str1[0] - '0')*10 + (str1[1] - '0');
            num2 = (str1[3] - '0')*10 + (str1[4] - '0');
            num3 = (str2[0] - '0')*10 + (str2[1] - '0');
            num4 = (str2[3] - '0')*10 + (str2[4] - '0');
            if (num1 < num3)
                return true;
            else if (num1 == num3)
            {
                if (num2 < num4)
                    return true;
            }
            return false;
        }

        public bool NoTimeOverlap(string FromTime, string ToTime, RoomAllocation prevAllocation)
        {
            if (LessThan(prevAllocation.FromTime, FromTime))
            {
                if (LessThan(FromTime, prevAllocation.ToTime))
                    return true;
                
            }
            else
            {
                if (LessThan(prevAllocation.FromTime, ToTime))
                    return true;
            }
            return false;
        }

        public ActionResult AllocateClassRoom(string CourseCode, string RoomNo, string Day, string FromTime, string ToTime)
        {
            
            int affectedRow = 0;
            if (CourseCode != null)
            {
                RoomAllocation prevAllocation = GetAllocationInfo(CourseCode);
                if (prevAllocation.Day != Day || NoTimeOverlap(FromTime, ToTime, prevAllocation) == false)
                {
                    newDatabaseGateway.Command.CommandText = "INSERT INTO ROOM_SCHEDULE VALUES('" + CourseCode + "','" + RoomNo + "','" + Day + "','" + FromTime + "','" + ToTime + "','True');";
                    newDatabaseGateway.Connection.Open();
                    affectedRow = newDatabaseGateway.Command.ExecuteNonQuery();
                    newDatabaseGateway.Connection.Close();
                    
                }
                if (affectedRow == 0)
                    ViewBag.message = "Error Found";
                else
                {
                    ViewBag.message = "Successfully Saved!!!!!";
                }
                
            }
            ViewBag.deptList = LoadDeptDropBox();
            ViewBag.rooms = GetAllRooms();
            ViewBag.days = GetAllDay();
            return View();
        }

        public JsonResult GetRoomScheduleByDepartment(string DeptCode)
        {
            List<RoomAllocation> allocations = new List<RoomAllocation>();
            string roomNo;
            newDatabaseGateway.Command.CommandText = "SELECT COURSE.CourseCode, CourseName, RoomNo, Day, FromTime, ToTime " +
                                                     "FROM COURSE FULL OUTER JOIN ROOM_SCHEDULE ON COURSE.CourseCode = ROOM_SCHEDULE.CourseCode " +
                                                     "WHERE DeptCode = '"+ DeptCode +"'  AND (Valid = 'True' OR Valid is NULL);";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                RoomAllocation allocation = new RoomAllocation();

                allocation.CourseCode = reader["CourseCode"].ToString();
                allocation.CourseName = reader["CourseName"].ToString();
                
                
                allocation.RoomNo = reader["RoomNo"].ToString();
                
                allocation.Day = reader["Day"].ToString();
                allocation.FromTime = reader["FromTime"].ToString();
                allocation.ToTime = reader["ToTime"].ToString();
                
                allocations.Add(allocation);
            }
            newDatabaseGateway.Connection.Close();
            string CourseCode = "";
            List<AllocationInfo> allocationList = new List<AllocationInfo>();
            AllocationInfo allocationInfo = new AllocationInfo();
            foreach (RoomAllocation roomAllocation in allocations)
            {
                if (CourseCode != roomAllocation.CourseCode)
                {
                    CourseCode = roomAllocation.CourseCode;
                    if (allocationInfo.CourseCode != null)
                    {
                        if (allocationInfo.CourseSchedule == null && allocationInfo.CourseCode != null && allocationInfo.CourseName != null)
                        {
                            allocationInfo.CourseSchedule = "Not Schedule Yet";
                        }
                        if(allocationInfo.CourseCode != null && allocationInfo.CourseName != null && allocationInfo.CourseSchedule != null)
                            allocationList.Add(allocationInfo);
                        allocationInfo = new AllocationInfo();
                    }
                    
                    allocationInfo.CourseCode = roomAllocation.CourseCode;
                    allocationInfo.CourseName = roomAllocation.CourseName;
                    if (roomAllocation.RoomNo != "")
                    {
                        allocationInfo.CourseSchedule =
                            "R.No:" + roomAllocation.RoomNo + "," + roomAllocation.Day + "," +
                            roomAllocation.FromTime + "-" + roomAllocation.ToTime;
                    }
                    
                    
                }
                else
                {
                    allocationInfo.CourseSchedule += "\n" + "R.No:" + roomAllocation.RoomNo + "," + roomAllocation.Day + "," +
                                                     roomAllocation.FromTime + "-" + roomAllocation.ToTime;
                }
            }
            if (allocationInfo.CourseSchedule == null && allocationInfo.CourseCode != null && allocationInfo.CourseName != null)
            {
                allocationInfo.CourseSchedule = "Not Schedule Yet";
            }
            if (allocationInfo.CourseCode != null && allocationInfo.CourseName != null && allocationInfo.CourseSchedule != null)
                allocationList.Add(allocationInfo);
            return Json(allocationList);
        }

        public ActionResult ClassRoomInfo()
        {
            ViewBag.deptList = LoadDeptDropBox();
            return View();
        }

        public ActionResult UnAllocateClassRoom()
        {
            int affectedRow = 0;
            newDatabaseGateway.Command.CommandText = "UPDATE ROOM_SCHEDULE SET Valid = 'False'";
            newDatabaseGateway.Connection.Open();
            newDatabaseGateway.Command.ExecuteNonQuery();
            newDatabaseGateway.Connection.Close();
            if (affectedRow == 0)
            {
                ViewBag.message = "Error!!";
            }
            else
            {
                ViewBag.message = "Successfully UnAllocated.!!!";
            }
            return View();
        }
    }
}

UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Views/ClassRoom/AllocateClassRoom.cshtml
@using UniversityCourseAndResultManagementSystemApp.Models

@{
    ViewBag.Title = "AllocateClassRoom";
    List<Department> deptList = ViewBag.deptList;
    List<int> rooms = ViewBag.rooms;
    List<string> days = ViewBag.days;
    string message = ViewBag.message;
}

<div id="container">
    <form id="AllocateClassRoom" class="well form-horizontal" method="GET">
        <fieldset>

            <legend><center><h2><b>ADD COURSE</b></h2></center></legend><br>

            @if (message != null)
            {
                <h3 align="center">@message</h3>
            }

            <div class="form-group">
                <label for="DeptCode" class="col-md-4 control-label">DEPARTMENT</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>

                        <select class="form-control selectpicker" id="DeptCode" name="DeptCode">
                            <option value="default">
                                ---SELECT--
                            </option>
                            @if (deptList != null)
                            {
                                foreach (Department department in deptList)
                                {
                                    <option value="@department.DeptCode">@department.DeptName</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label for="CourseCode" class="col-md-4 control-label">COURSE</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <select class="form-control selectpicker" id="CourseCode" name="CourseCode">
                            <option value="default">
                                ---SELECT--
                            </option>

                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="RoomNo" class="col-md-4 control-label">ROOM NO.</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <select class="form-control selectpicker" id="RoomNo" name="RoomNo">
                            <option value="default">
                                ---SELECT--
                            </option>
                            @if (rooms != null)
                            {
                                foreach (int room in rooms)
                                {
                                    <option value="@room">@room</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="Day" class="col-md-4 control-label">DAY</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <select class="form-control selectpicker" id="Day" name="Day">
                            <option value="default">
                                ---SELECT--
                            </option>
                            @if (days != null)
                            {
                                foreach (string day in days)
                                {
                                    <option value="@day">@day</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="FromTime" class="col-md-4 control-label">FROM</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <input name="FromTime" id="FromTime" placeholder="" class="form-control" type="time" />
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="ToTime" class="col-md-4 control-label">TO</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <input name="ToTime" id="ToTime" placeholder="" class="form-control" type="time" />
                    </div>
                </div>
            </div>




            <div class="form-group">
                <label class="col-md-4 control-label"></label>
                <div class="col-md-4" style="margin-left: 54%;">
                    <br>
                    <button type="submit" class="btn btn-warning">SAVE COURSE<span class="glyphicon glyphicon-send"></span></button>
                </div>
            </div>

            <!-- Success message -->
            <div class="alert alert-success" role="alert" id="success_message">Success <i class="glyphicon glyphicon-thumbs-up"></i> Success!.</div>


        </fieldset>
    </form>

</div>

@section scripts
{
<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {
            

            $("#DeptCode").change(function () {
                var DeptCode = $("#DeptCode").val();
                var json = { StudentDept: DeptCode };
                $("#CourseCode").empty();
                $("#CourseCode").append('<option value="default">---SELECT---</option>');
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCoursesByDepartment", "Student")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $.each(data, function (key, value) {
                            $("#CourseCode").append('<option value="' + value.CourseCode + '">' + value.CourseCode + '</option>');
                        });
                    }
                });
                
            });

            $.validator.addMethod("valueNotEquals", function (value, element, arg) {
                return arg !== value;
            }, "Value must not equal arg.");

            $.validator.addMethod("timey", function (value, element, arg) {
                var hour = parseInt(value.substring(0, 2));
                return hour > 7 && hour < 23;
            }, "Invalid time");

            $("#AllocateClassRoom").validate({
                rules: {
                    DeptCode: { valueNotEquals: "default" },
                    CourseCode: { valueNotEquals: "default" },
                    RoomNo: { valueNotEquals: "default" },
                    Day: { valueNotEquals: "default" },
                    FromTime: { timey: "s" },
                    ToTime: { timey: "s" }
                },
                messages: {
                    DeptCode: { valueNotEquals: "Please select Department!" },
                    CourseCode: { valueNotEquals: "Please select Course!" },
                    RoomNo: { valueNotEquals: "Please select Room No!" },
                    Day: { valueNotEquals: "Please select WeekDay!" },
                    FromTime: { timey: "Please select From Time!" },
                    ToTime: { timey: "Please select To Time!" }
                }

            });


        });
    </script>
}

UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Views/ClassRoom/ClassRoomInfo.cshtml
@using UniversityCourseAndResultManagementSystemApp.Models

@{
    ViewBag.Title = "ClassRoomInfo";
    List<Department> deptList = ViewBag.deptList;
}

<div id="container">
    <form id="SaveCourse" class="well form-horizontal" method="GET">
        <fieldset>

            <legend><center><h2><b>CLASS ROOM AND SCHEDULE</b></h2></center></legend><br>


            <div class="form-group">
                <label for="DeptCode" class="col-md-4 control-label">DEPARTMENT</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>

                        <select class="form-control selectpicker" id="DeptCode" name="DeptCode">
                            <option value="">
                                ---SELECT--
                            </option>
                            @if (deptList != null)
                            {
                                foreach (Department department in deptList)
                                {
                                    <option value="@department.DeptCode">@department.DeptName</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>


            <!-- Success message -->
            <div class="alert alert-success" role="alert" id="success_message">Success <i class="glyphicon glyphicon-thumbs-up"></i> Success!.</div>
            
            
            <table class ="table table-fixed">
                <thead>
                <tr>
                    <th class="col-xs-2">SL</th>
                    <th class="col-xs-2">COURSE CODE</th>
                    <th class="col-xs-4">COURSE NAME</th>
                    <th class="col-xs-4" >SCHEDULE INFO</th>
                </tr>
                </thead>
                <tbody id="classScheduleTableBody">
                
                </tbody>
            </table>

        </fieldset>
    </form>

</div>


@section scripts
{
    <script>
        $(document).ready(function () {


            $("#DeptCode").change(function () {

                
                $("#classScheduleTableBody").empty();
                var DeptCode = $("#DeptCode").val();
                var json = { DeptCode: DeptCode };
                var serial = 1;
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetRoomScheduleByDepartment", "ClassRoom")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $.each(data, function (key, value) {
                            $("#classScheduleTableBody").append('<tr><td class="col-xs-2">' + serial + '</td><td class="col-xs-2">' + value.CourseCode + '</td><td class="col-xs-4">' + value.CourseName + '</td><td class="col-xs-4">' + value.CourseSchedule + '</td></tr>');
                            serial++;
                        });
                    }

                });
            });
        });
    </script>
}

UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Views/ClassRoom/UnAllocateClassRoom.cshtml
@{
    ViewBag.Title = "UnAllocateClassRoom";
    string message = ViewBag.message;
}

<div class="container">

    <form id="EnrollCourse" class="well form-horizontal" method="POST">
        <fieldset>

            <legend><center><h2><b>UNALLOCATE ALL CLASS ROOM</b></h2></center></legend><br>
            
            @if (message != null)
            {
                <h3 align="center">@message</h3>
            }


            <div class="form-group">
                <label class="col-md-4 control-label"></label>
                <div class="col-md-4" style="margin-left: 54%;">
                    <br>
                    <button type="submit" class="btn btn-warning"> UNALLOCATE ALL CLASS ROOM <span class="glyphicon glyphicon-send"></span></button>
                </div>
            </div>
        </fieldset>
    </form>
</div>