UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using UniversityCourseAndResultManagementSystemApp.Gateway;
using UniversityCourseAndResultManagementSystemApp.Models;

namespace UniversityCourseAndResultManagementSystemApp.Controllers
{
    public class ResultController : Controller
    {
        private DatabaseGateway newDatabaseGateway = new DatabaseGateway();

        List<string> GetAllRegNo()
        {
            List<string> regNoList = new List<string>();
            newDatabaseGateway.Command.CommandText = "SELECT StudentRegNo FROM STUDENT;";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                regNoList.Add(reader["StudentRegNo"].ToString());
            }
            newDatabaseGateway.Connection.Close();
            return regNoList;
        }

        List<string> GetAllGrade()
        {
            List<string> gradeLetters = new List<string>();
            newDatabaseGateway.Command.CommandText = "SELECT GradeLetter FROM GRADE;";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                gradeLetters.Add(reader["GradeLetter"].ToString());
            }
            newDatabaseGateway.Connection.Close();
            return gradeLetters;
        }

        public JsonResult GetCoursesByStudent(string StudentRegNo)
        {
            List<Course> courses = new List<Course>();
            newDatabaseGateway.Command.CommandText = "SELECT CourseCode FROM ENDROLLMENT WHERE StudentRegNo = '" + StudentRegNo + "';";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                Course newCourse = new Course
                {
                    CourseCode = reader["CourseCode"].ToString()
                };
                courses.Add(newCourse);
            }
            newDatabaseGateway.Connection.Close();
            return Json(courses);

        }



        public JsonResult GetStudentByStudentRegNo(string StudentRegNo)
        {
            Student newStudent = new Student();
            newDatabaseGateway.Command.CommandText =
                "SELECT StudentName, StudentEmail, StudentDept FROM STUDENT WHERE StudentRegNo = '" + StudentRegNo + "';";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                newStudent.StudentName = reader["StudentName"].ToString();
                newStudent.StudentEmail = reader["StudentEmail"].ToString();
                newStudent.StudentDept = reader["StudentDept"].ToString();
            }
            newDatabaseGateway.Connection.Close();
            ViewBag.student = newStudent;
            return Json(newStudent);
        }

        public JsonResult GetResultByStudent(string StudentRegNo)
        {
            TempData["StudentRegNo"] = StudentRegNo;
            List<Grade> grades = new List<Grade>();
            newDatabaseGateway.Command.CommandText =
                "SELECT COURSE.CourseCode, CourseName, Grade FROM COURSE, ENDROLLMENT WHERE COURSE.CourseCode = ENDROLLMENT.CourseCode AND StudentRegNo = '"+ StudentRegNo +"';";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                Grade newGrade = new Grade
                {
                    CourseCode = reader["CourseCode"].ToString(),
                    CourseName = reader["CourseName"].ToString(),
                    CourseGrade = reader["Grade"].ToString()
                };
                grades.Add(newGrade);
            }
            newDatabaseGateway.Connection.Close();
            return Json(grades);
        }

        public ActionResult SaveStudentResult(Student student, string CourseCode, string GradeLetter)
        {
            int affectedRow = 0;
            if (student.StudentRegNo != null && CourseCode != null && GradeLetter != null)
            {
                newDatabaseGateway.Command.CommandText = "UPDATE ENDROLLMENT SET Grade = '" + GradeLetter + "' WHERE StudentRegNo = '" + student.StudentRegNo + "' and CourseCode = '" + CourseCode + "';";
                newDatabaseGateway.Connection.Open();
                affectedRow = newDatabaseGateway.Command.ExecuteNonQuery();
                newDatabaseGateway.Connection.Close();
                if (affectedRow == 0)
                {
                    ViewBag.message = "Error !!!";
                }
                else
                {
                    ViewBag.message = "Successfully Saved. !!!";
                }
            }
            ViewBag.regNoList = GetAllRegNo();
            ViewBag.gradeLetters = GetAllGrade();
            return View();
        }

        public ActionResult ViewResult()
        {
            TempData["StudentRegNo"] = "";
            ViewBag.regNoList = GetAllRegNo();
            return View();
        }



        public void GenerateResultPDF()
        {
            string StudentRegNo = (string) TempData["StudentRegNo"];

            Student student = new Student();
            newDatabaseGateway.Command.CommandText =
                "SELECT StudentName, StudentEmail, StudentDept FROM STUDENT WHERE StudentRegNo = '" + StudentRegNo + "';";
            newDatabaseGateway.Connection.Open();
            SqlDataReader reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                student.StudentName = reader["StudentName"].ToString();
                student.StudentEmail = reader["StudentEmail"].ToString();
                student.StudentDept = reader["StudentDept"].ToString();
            }
            newDatabaseGateway.Connection.Close();

            List<Grade> grades = new List<Grade>();
            newDatabaseGateway.Command.CommandText =
                "SELECT COURSE.CourseCode, CourseName, Grade, CourseCredit FROM COURSE, ENDROLLMENT WHERE COURSE.CourseCode = ENDROLLMENT.CourseCode AND StudentRegNo = '" + StudentRegNo + "';";
            newDatabaseGateway.Connection.Open();
            reader = newDatabaseGateway.Command.ExecuteReader();
            while (reader.Read())
            {
                Grade newGrade = new Grade
                {
                    CourseCode = reader["CourseCode"].ToString(),
                    CourseName = reader["CourseName"].ToString(),
                    CourseGrade = reader["Grade"].ToString(),
                    CourseCredit = Convert.ToDouble(reader["CourseCredit"].ToString())
                };
                grades.Add(newGrade);
            }
            newDatabaseGateway.Connection.Close();

            Dictionary<string, double> gradePoint = new Dictionary<string, double>();
            gradePoint["A+"] = 4.00;
            gradePoint["A"] = 4.00;
            gradePoint["A-"] = 3.70;
            gradePoint["B+"] = 3.30;
            gradePoint["B"] = 3.00;
            gradePoint["B-"] = 2.70;
            gradePoint["C+"] = 2.30;
            gradePoint["C"] = 2.00;
            gradePoint["C-"] = 1.70;
            gradePoint["D+"] = 1.30;
            gradePoint["D"] = 1.00;
            gradePoint["F"] = 0.00;
            gradePoint["Not Graded Yet"] = 0.00;

            double totalGp = 0.00;
            double totalCr = 0.00;
            double cgpa = 0.00;

            using (StringWriter sw = new StringWriter())
            {
                using (HtmlTextWriter hw = new HtmlTextWriter(sw))
                {
                    StringBuilder sb = new StringBuilder();
                    

                    //Generate Invoice (Bill) Header.
                    /*sb.Append("<table width='90%' border='0' align='center' cellpadding='0' cellspacing='0'>");
                    sb.Append("<tr><td><table width='100%' border='0' cellspacing='0' cellpadding='0' ><tr>");
                    sb.Append("<td width='50%'>Student ID: <strong>2014-3-60-044</strong><br />Student Name: <strong>Md. Solaiman Hosen</strong><br />Objective: <strong>B.Sc. in  Computer Science and Engineering</strong></td>");
                    sb.Append("<td width='50%' align='left' valign='top'><strong> <u> Status</u></strong><br /></td></tr></table><hr/></td></tr>");
		
                    sb.Append("<tr><td align='left'><table width='80%' border='0' cellspacing='0' cellpadding='0' >");
                    sb.Append("<tr><td width='9%'><strong>Course</strong></td><td width='43%'><strong>Title of the course </strong></td><td width='10%' align='center'><strong>Credit</strong></td>");
                    sb.Append("<td width='12%' align='center'><strong>Grade</strong></td><td width='16%' align='center'><strong>Grade Point </strong></td><td width='10%' align='center'><strong>gpacr</strong></td></tr>");
	  
                    //sb.Append("_____________________________________________________________________________________________");

                    sb.Append("<tr><td>MAT101</td>");
                    sb.Append("<td>Differential & Integral Calculus</td>");
                    sb.Append("<td align='center'>3</td>");
                    sb.Append("<td align='center'>A-</td>");
                    sb.Append("<td align='center'>3.7</td>");
                    sb.Append("<td align='center'>3</td></tr>");
		
                   // sb.Append("______________________________________________________________________________");

UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Views/Result/SaveStudentResult.cshtml
@{
    ViewBag.Title = "SaveStudentResult";
    List<string> regNoList = ViewBag.regNoList;
    List<string> gradeLetters = ViewBag.gradeLetters;
    string message = ViewBag.message;
}

<div class="container">


    <form id="SaveStudentResult" class="well form-horizontal" method="POST">
        <fieldset>
            <!-- Form Name -->
            <legend><center><h2><b>SAVE STUDENT RESULT</b></h2></center></legend><br>

            @if (message != null)
            {
                <h3 align="center">@message</h3>
            }

            <div class="form-group">
                <label for="StudentRegNo" class="col-md-4 control-label">Student.Reg.NO</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>

                        <select class="form-control selectpicker" id="StudentRegNo" name="StudentRegNo">
                            <option value="default">
                                ---SELECT--
                            </option>
                            @if (regNoList != null)
                            {
                                foreach (string regNo in regNoList)
                                {
                                    <option value="@regNo">@regNo</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="StudentName" class="col-md-4 control-label">Name</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <input name="StudentName" id="StudentName" placeholder="" class="form-control" type="text" readonly />
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label for="StudentEmail" class="col-md-4 control-label">Email</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <input name="StudentEmail" id="StudentEmail" placeholder="" class="form-control" type="text" readonly />
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="StudentDept" class="col-md-4 control-label">Depertment</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <input name="StudentDept" id="StudentDept" placeholder="" class="form-control" type="text" readonly />
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="CourseCode" class="col-md-4 control-label">Select Course</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>

                        <select class="form-control selectpicker" id="CourseCode" name="CourseCode">
                            <option value="default">
                                ---SELECT--
                            </option>
                        </select>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label for="GradeLetter" class="col-md-4 control-label">Select grade Letters</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>

                        <select class="form-control selectpicker" id="GradeLetter" name="GradeLetter">
                            <option value="default">
                                ---SELECT--
                            </option>
                            @if (gradeLetters != null)
                            {
                                foreach (string gradeLetter in gradeLetters)
                                {
                                    <option value="@gradeLetter">@gradeLetter</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label"></label>
                <div class="col-md-4" style="margin-left: 54%;">
                    <br>
                    <button type="submit" class="btn btn-warning"> Save <span class="glyphicon glyphicon-send"></span></button>
                </div>
            </div>




        </fieldset>
    </form>
    <br/><br /><br /><br /><br /><br /><br /><br />
</div>


@section scripts
{
<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {


            $("#StudentRegNo").change(function () {
                var StudentRegNo = $("#StudentRegNo").val();
                var json = { StudentRegNo: StudentRegNo };
                $("#CourseCode").empty();
                $("#CourseCode").append('<option value="default">---SELECT---</option>');
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCoursesByStudent", "Result")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        //alert(data);
                        $.each(data, function (key, value) {
                            //alert(value.CourseCode);
                            $("#CourseCode").append('<option value="' + value.CourseCode + '">' + value.CourseCode + '</option>');
                        });
                    }
                });
                var StudentRegNo = $("#StudentRegNo").val();
                var json = { StudentRegNo: StudentRegNo };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentByStudentRegNo", "Result")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $('input[name="StudentName"]').val(data.StudentName);
                        $('input[name="StudentEmail"]').val(data.StudentEmail);
                        $('input[name="StudentDept"]').val(data.StudentDept);
                    }

                });

            });

            $.validator.addMethod("valueNotEquals", function (value, element, arg) {
                return arg !== value;
            }, "Value must not equal arg.");

            $("#SaveStudentResult").validate({
                rules: {
                    StudentRegNo: { valueNotEquals: "default" },
                    CourseCode: { valueNotEquals: "default" },
                    GradeLetter: { valueNotEquals: "default" }
                },
                messages: {
                    StudentRegNo: { valueNotEquals: "Please select Student!" },
                    CourseCode: { valueNotEquals: "Please select Course!" },
                    GradeLetter: { valueNotEquals: "Please select Grade!" }
                }

            });
        });
    </script>
}

UniversityCourseAndResultManagementSystemApp/UniversityCourseAndResultManagementSystemApp/Views/Result/ViewResult.cshtml
@{
    ViewBag.Title = "ViewResult";
    List<string> regNoList = ViewBag.regNoList;
}

<div class="container">


    <form id="ViewResult" class="well form-horizontal" method="POST">
        <fieldset>
            
            <legend><center><h2><b>VIEW RESULT</b></h2></center></legend><br>

           
            
            <div class="form-group">
                <label for="StudentRegNo" class="col-md-4 control-label">Student.Reg.NO</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>

                        <select class="form-control selectpicker" id="StudentRegNo" name="StudentRegNo">
                            <option value="">
                                ---SELECT--
                            </option>
                            @if (regNoList != null)
                            {
                                foreach (string regNo in regNoList)
                                {
                                    <option value="@regNo">@regNo</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="StudentName" class="col-md-4 control-label">Name</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <input name="StudentName" id="StudentName" placeholder="" class="form-control" type="text" />
                    </div>
                </div>
            </div>

           
            <div class="form-group">
                <label for="Email" class="col-md-4 control-label">Email</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <input name="StudentEmail" id="StudentEmail" placeholder="" class="form-control" type="text" />
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="StudentDept" class="col-md-4 control-label">Depertment</label>
                <div class="col-md-4 inputGroupContainer">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                        <input name="StudentDept" id="StudentDept" placeholder="" class="form-control" type="text" />
                    </div>
                </div>
            </div>
            
           
            <div class="form-group">
                <label class="col-md-4 control-label"></label>
                <div class="col-md-4" style="margin-left: 54%;">
                    <br>
                   <input type="button" value="Make PDF" onclick="location.href = '@Url.Action("GenerateResultPDF", "Result")'" class="btn btn-warning"/> 
                    

                </div>
            </div>
            
            <table class ="table table-fixed">
                <thead>
                <tr>
                    <th class="col-xs-3">SL</th>
                    <th class="col-xs-3">COURSE CODE</th>
                    <th class="col-xs-3">COURSE NAME</th>
                    <th class="col-xs-3" >GRADE</th>
                </tr>
                </thead>
                <tbody id="resultTableBody">
                
                </tbody>
            </table>
                
           


        </fieldset>
    </form>
</div>

@section scripts
{
    <script>
    $(document).ready(function () {

        
        $("#StudentRegNo").change(function () {

            var StudentRegNo = $("#StudentRegNo").val();
            var json = { StudentRegNo: StudentRegNo };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetStudentByStudentRegNo", "Student")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $('input[name="StudentName"]').val(data.StudentName);
                        $('input[name="StudentEmail"]').val(data.StudentEmail);
                        $('input[name="StudentDept"]').val(data.StudentDept);
                    }

            });
            $("#resultTableBody").empty();
                var StudentRegNo = $("#StudentRegNo").val();
                var json = { StudentRegNo: StudentRegNo };
            var serial = 1;
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetResultByStudent", "Result")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $.each(data, function (key, value) {
                            $("#resultTableBody").append('<tr><td class="col-xs-3">' + serial + '</td><td class="col-xs-3">' + value.CourseCode + '</td><td class="col-xs-3">' + value.CourseName + '</td><td class="col-xs-3">' + value.CourseGrade + '</td></tr>');
                            serial++;
                        });
                    }

                });
            });
        });
    </script>
}